id: P004141
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:55:53.402780
source_metadata:
  id: bdr:W20913
  title: སྤྱོད་འཇུག་འགྲེལ་པ་རིན་པོ་ཆེའི་ཕྲེང་བ།
  author: ''
  volumes:
    8d543212bbb847399a1652187fdd644f:
      image_group_id: I1KG9557
      title: ''
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
